# Name of workflow
name: Build workflow

# When workflow is triggered
# on:
#   push:
#     branches:
#       - main

on:
  workflow_dispatch:

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      # Install NodeJS
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      # Run npm install and build on our code
      - run: npm ci
      - name: Build
        run: npm run build --if-present
        env:
          CI: false
          
      - name: Netlify Deploy Action
        # You may pin to the exact commit or the version.
        # uses: South-Paw/action-netlify-deploy@07ce8475462daf885db65d4450cee7ebcf5b2943
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          # GitHub token
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Your Netlify personal access token (Please save it as a secret in your repo!)
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          # Your Netlify site's `API ID`
          netlify-site-id: ${{ secrets.NETLIFY_SIDE_ID }}
          # The folder of the site want to deploy
          build-dir: "./build"
